TrajectoryPlannerROS:
 max_vel_x: 0.15
 min_vel_x: 0.05
 max_vel_theta: 1.0
 min_vel_theta: -1.0
 min_in_place_vel_theta: 0.25
 acc_lim_theta: 1.0
 acc_lim_x: 1.5
 acc_lim_Y: 1.5
 holonomic_robot: false
 meter_scoring: true 
 xy_goal_tolerance: 0.1
 yaw_goal_tolerance: 3.14
 meter_scoring: true
 occdist_scale:  0.01
 pdist_scale: 0.3
 gdist_scale: 0.2